// Wave G — wiki_agent_schema generator.
//
// Produces the agent-facing retrieval surface for a wiki: one row per
// `kind` in wiki_agent_schema. v0.2.0 ships two kinds, `description`
// (direct embedding of wikis.description) and `hyde_synthetic` (HyDE
// hypothetical document generated by an LLM, then embedded). Future
// kinds drop in as additional rows without schema change.
//
// Per docs/architecture/wiki-agent-schema.md.

import { and, eq, sql } from 'drizzle-orm'
import { embedText, type OpenRouterConfig } from '@robin/agent'
import type { DB } from '../db/client.js'
import { wikis, wikiTypes, wikiAgentSchema } from '../db/schema.js'
import { logger } from './logger.js'

const log = logger.child({ component: 'wiki-agent-schema' })

/**
 * Current generator version. Bump when any of these change: prompt
 * template, framing string semantics, embedding model, generator LLM.
 * Wikis whose stored generator_version trails this string surface in
 * /settings/outstanding for incremental backfill.
 */
export const GENERATOR_VERSION = 'hyde_v1'

/** Hard ceiling on the body excerpt fed into the HyDE prompt. */
export const HYDE_BODY_EXCERPT_CHARS = 800

/**
 * Upsert the `kind='description'` row for a wiki. Caller supplies the
 * already-computed embedding so this stays free of LLM calls and is
 * safe to invoke from the POST/PUT request path.
 *
 * Idempotent on (wiki_key, kind). Re-running with the same content/embedding
 * is a no-op aside from the bumped generated_at timestamp.
 */
export async function upsertDescriptionAgentSchemaRow(
  database: DB,
  wikiKey: string,
  description: string,
  embedding: number[]
): Promise<void> {
  await database
    .insert(wikiAgentSchema)
    .values({
      wikiKey,
      kind: 'description',
      content: description,
      embedding,
      generatorVersion: GENERATOR_VERSION,
    })
    .onConflictDoUpdate({
      target: [wikiAgentSchema.wikiKey, wikiAgentSchema.kind],
      set: {
        content: description,
        embedding,
        generatorVersion: GENERATOR_VERSION,
        generatedAt: new Date(),
      },
    })
}

/**
 * Delete the `kind='hyde_synthetic'` row for a wiki. Used by PUT /wikis/:id
 * when the description changes to invalidate the now-stale HyDE passage.
 * The heal worker recreates it asynchronously (the HyDE call is an LLM
 * round-trip, too expensive for the request path).
 *
 * Idempotent: deleting a missing row is a no-op.
 */
export async function deleteHydeAgentSchemaRow(
  database: DB,
  wikiKey: string
): Promise<void> {
  await database
    .delete(wikiAgentSchema)
    .where(
      and(
        eq(wikiAgentSchema.wikiKey, wikiKey),
        eq(wikiAgentSchema.kind, 'hyde_synthetic')
      )
    )
}

/**
 * The structured HyDE template per docs/architecture/wiki-agent-schema.md.
 * The template is rendered with:
 *
 *   wiki_type        — wiki.type slug, lowercase
 *   title            — wikis.name
 *   description      — wikis.description
 *   source_excerpt   — first HYDE_BODY_EXCERPT_CHARS chars of wikis.content
 *   internal_framing — wiki_types.internal_framing (per-type framing string)
 *
 * The MUST-NOT block is hard grounding: the LLM is forbidden from
 * introducing claims not present in the source. Combined with the
 * type-aware framing, this addresses the three failure modes naive HyDE
 * exhibits — vocabulary collapse, drift, and register mismatch.
 */
export function renderHydePrompt(args: {
  wikiType: string
  title: string
  description: string
  sourceExcerpt: string
  internalFraming: string
}): string {
  return `[CONTEXT]
Wiki type: ${args.wikiType}
Title: ${args.title}
Description: ${args.description}
Source excerpt: ${args.sourceExcerpt}

[TASK]
Generate a synthetic retrieval-optimized passage for this wiki. The
passage will be embedded and used to match user queries against this
wiki at search time.

The passage MUST:
- Cover 3 to 5 questions a non-expert would naturally ask about this topic
- Use the vocabulary the user would use, not the jargon in the source
- Stay grounded in claims present in the source
- Read in the register appropriate for a ${args.wikiType} wiki:
  ${args.internalFraming}

The passage MUST NOT:
- Introduce claims not present in the source
- Use meta-language like "this wiki" or "this document"
- Exceed 200 words

[OUTPUT]
Write the passage now. No preamble, no headers, prose only.`
}

/**
 * Look up the configured HyDE generator model. Per the architecture doc
 * this is the RETRIEVAL_INDEX_MODEL env var, defaulting to the writer
 * model (which the regen pipeline already loads). The model is intended
 * to be capable since this runs once per wiki per regen, not on every
 * user interaction.
 */
export function resolveRetrievalIndexModel(orConfig: OpenRouterConfig): string {
  const fromEnv = process.env.RETRIEVAL_INDEX_MODEL
  if (fromEnv && fromEnv.trim().length > 0) return fromEnv
  return orConfig.models.wikiGeneration
}

/**
 * Call the HyDE LLM. Returns the generated passage as plain text,
 * stripped of leading/trailing whitespace. Returns null on failure so
 * the caller can fall back to skipping the hyde_synthetic row rather
 * than aborting the entire regen.
 */
export type HydeCaller = (prompt: string, model: string) => Promise<string | null>

interface GenerateAgentSchemaArgs {
  wikiKey: string
  orConfig: OpenRouterConfig
  /**
   * Caller for the HyDE LLM. Injected for testability — production
   * wiring uses a thin wrapper over the OpenRouter SDK; tests pass a
   * deterministic stub.
   */
  hydeCaller: HydeCaller
}

interface GenerateAgentSchemaResult {
  /** Whether a description-kind row was written. */
  wroteDescription: boolean
  /** Whether a hyde_synthetic-kind row was written. */
  wroteHyde: boolean
  /** Generator version stamped on rows from this run. */
  version: string
  /** Wall-clock total in ms (excludes the parent regen flow). */
  totalMs: number
}

/**
 * Regenerate every kind in wiki_agent_schema for a single wiki. Idempotent
 * per (wiki_key, kind, generator_version). The `description` kind is a
 * direct embedding of wikis.description; the `hyde_synthetic` kind runs
 * through the HyDE template + LLM + embedding pipeline.
 *
 * Failure of the hyde_synthetic stage does NOT abort description-kind
 * generation. Retrieval falls back to BM25 + description-kind when
 * hyde_synthetic is missing.
 */
export async function generateWikiAgentSchema(
  database: DB,
  args: GenerateAgentSchemaArgs
): Promise<GenerateAgentSchemaResult> {
  const t0 = performance.now()
  const { wikiKey, orConfig, hydeCaller } = args
  const result: GenerateAgentSchemaResult = {
    wroteDescription: false,
    wroteHyde: false,
    version: GENERATOR_VERSION,
    totalMs: 0,
  }

  const [wiki] = await database
    .select({
      type: wikis.type,
      name: wikis.name,
      description: wikis.description,
      content: wikis.content,
    })
    .from(wikis)
    .where(eq(wikis.lookupKey, wikiKey))
  if (!wiki) {
    log.warn({ wikiKey }, 'wiki not found, skipping agent-schema generation')
    result.totalMs = performance.now() - t0
    return result
  }

  // ── description kind: direct embedding of wikis.description ──
  if (wiki.description && wiki.description.trim().length > 0) {
    const descVec = await embedText(wiki.description, {
      apiKey: orConfig.apiKey,
      model: orConfig.models.embedding,
    })
    if (descVec) {
      await upsertDescriptionAgentSchemaRow(database, wikiKey, wiki.description, descVec)
      result.wroteDescription = true
    } else {
      log.warn({ wikiKey }, 'description embedding returned null, skipping description kind')
    }
  } else {
    log.debug({ wikiKey }, 'description empty, skipping description kind')
  }

  // ── hyde_synthetic kind: LLM-generated hypothetical document, then embedded ──
  // Look up internal_framing on the wiki's type. NULL framing means the
  // type does not yet ship with framing on disk — fall back to a generic
  // type-naming framing rather than blowing up.
  const [framingRow] = await database
    .select({ internalFraming: wikiTypes.internalFraming })
    .from(wikiTypes)
    .where(eq(wikiTypes.slug, wiki.type))

  const internalFraming =
    framingRow?.internalFraming && framingRow.internalFraming.trim().length > 0
      ? framingRow.internalFraming
      : `Write in the register appropriate for a ${wiki.type} wiki.`

  const sourceExcerpt = (wiki.content ?? '').slice(0, HYDE_BODY_EXCERPT_CHARS)

  const prompt = renderHydePrompt({
    wikiType: wiki.type,
    title: wiki.name,
    description: wiki.description ?? '',
    sourceExcerpt,
    internalFraming,
  })

  const model = resolveRetrievalIndexModel(orConfig)

  let hydeText: string | null = null
  try {
    hydeText = await hydeCaller(prompt, model)
  } catch (err) {
    log.warn(
      { wikiKey, err: err instanceof Error ? err.message : String(err) },
      'hyde generator threw, skipping hyde_synthetic kind'
    )
    hydeText = null
  }

  if (hydeText && hydeText.trim().length > 0) {
    const trimmed = hydeText.trim()
    const hydeVec = await embedText(trimmed, {
      apiKey: orConfig.apiKey,
      model: orConfig.models.embedding,
    })
    if (hydeVec) {
      await database
        .insert(wikiAgentSchema)
        .values({
          wikiKey,
          kind: 'hyde_synthetic',
          content: trimmed,
          embedding: hydeVec,
          generatorVersion: GENERATOR_VERSION,
        })
        .onConflictDoUpdate({
          target: [wikiAgentSchema.wikiKey, wikiAgentSchema.kind],
          set: {
            content: trimmed,
            embedding: hydeVec,
            generatorVersion: GENERATOR_VERSION,
            generatedAt: new Date(),
          },
        })
      result.wroteHyde = true
    } else {
      log.warn({ wikiKey }, 'hyde embedding returned null, skipping hyde_synthetic kind')
    }
  }

  result.totalMs = performance.now() - t0
  log.info(
    {
      wikiKey,
      wroteDescription: result.wroteDescription,
      wroteHyde: result.wroteHyde,
      ms: Math.round(result.totalMs),
    },
    'wiki agent schema generated'
  )
  return result
}

/**
 * Count rows in wiki_agent_schema whose generator_version trails the
 * canonical version. Used by /settings/outstanding to surface backfill
 * opportunities.
 */
export async function countOutstandingAgentSchemaWikis(
  database: DB
): Promise<number> {
  // A wiki is outstanding if it has zero rows at the current version.
  // Use a single SQL aggregation rather than two queries — one count of
  // wikis whose latest row trails or is missing.
  const rows = await database.execute<{ count: number }>(sql`
    SELECT COUNT(DISTINCT w.lookup_key)::int AS count
    FROM ${wikis} AS w
    LEFT JOIN ${wikiAgentSchema} AS a
      ON a.wiki_key = w.lookup_key
      AND a.generator_version = ${GENERATOR_VERSION}
      AND a.kind = 'hyde_synthetic'
    WHERE w.deleted_at IS NULL
      AND a.wiki_key IS NULL
  `)
  return Number(rows[0]?.count ?? 0)
}

/**
 * Wiki keys that need a kind='description' row written or refreshed.
 * Targets two failure cases:
 *
 *   1. The description row is missing entirely (newly-created wikis pre-fix
 *      or wikis that pre-date the create-time bootstrap in POST /wikis).
 *   2. The description row exists but its embedding is NULL (the create-time
 *      embed call failed and the heal pass needs to retry).
 *
 * Soft-deleted wikis are excluded. Wikis with empty description are excluded;
 * there is nothing to embed.
 */
export async function findWikisMissingDescriptionRow(
  database: DB,
  limit: number
): Promise<Array<{ wikiKey: string; description: string }>> {
  const rows = await database.execute<{ wiki_key: string; description: string }>(sql`
    SELECT w.lookup_key AS wiki_key, w.description AS description
    FROM ${wikis} AS w
    LEFT JOIN ${wikiAgentSchema} AS a
      ON a.wiki_key = w.lookup_key AND a.kind = 'description'
    WHERE w.deleted_at IS NULL
      AND w.description IS NOT NULL
      AND length(trim(w.description)) > 0
      AND (a.wiki_key IS NULL OR a.embedding IS NULL)
    ORDER BY w.created_at ASC
    LIMIT ${limit}
  `)
  return rows.map((r) => ({ wikiKey: r.wiki_key, description: r.description }))
}

/**
 * Wiki keys that need a kind='hyde_synthetic' row written. Targets the case
 * where the wiki has no row at all for this kind. The HyDE call is gated on
 * description being present so the prompt has a usable [CONTEXT] block.
 */
export async function findWikisMissingHydeRow(
  database: DB,
  limit: number
): Promise<string[]> {
  const rows = await database.execute<{ wiki_key: string }>(sql`
    SELECT w.lookup_key AS wiki_key
    FROM ${wikis} AS w
    LEFT JOIN ${wikiAgentSchema} AS a
      ON a.wiki_key = w.lookup_key AND a.kind = 'hyde_synthetic'
    WHERE w.deleted_at IS NULL
      AND w.description IS NOT NULL
      AND length(trim(w.description)) > 0
      AND a.wiki_key IS NULL
    ORDER BY w.created_at ASC
    LIMIT ${limit}
  `)
  return rows.map((r) => r.wiki_key)
}
